name: Production Deploy

on:
  push:
    branches: [ main ]

jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials (Production)
      run: |
        az aks get-credentials -n ${{ secrets.PRODUCTION_CLUSTER_NAME }} -g ${{ secrets.RESOURCE_GROUP }} --overwrite-existing

    - name: Deploy to Production
      run: |
        SHA=${{ github.sha }}
        for f in k8s/*.yaml; do
          sed -i "s|<IMAGE_TAG>|$SHA|g" $f
        done
        kubectl apply -f k8s/
        kubectl get pods -o wide
        kubectl get svc
